### ISSUE TITLE
Documentation for devs

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#1]
Hello!

I've been having some issues with your (and other) extension(s) and am trying to build it.

I figured that perhaps you'd want a suggestion with some sort of tutorial on how to set up the environment to build your extension and such, for example, starting with not using a relative path as the `evscode` dependency, using the git url maybe?

Anyway, just suggestions if you feel like it!

**Comment by pustaczek** [comment]
Hi!

Thanks for the suggestion. I fixed the path thing and created [CONTRIBUTING.md](https://github.com/pustaczek/icie/blob/master/CONTRIBUTING.md) where I tried to cover the basics of the build system. Did you have any other issues?

**Comment by mikaelmello** [comment]
Nope, that was all, additional issues included not having `vsce` or a nightly Rust build, but that's already there, thanks!

By the way, is is possible to debug (line-by-line) the Rust code of the extension?

**Comment by pustaczek** [comment]
The Rust code runs in a subprocess, so it is possible to attach gdb to a running extension. Check the PID of the extension process(something.../data/bin/linux) and run e.g. `gdb -p 29379`. I just checked and it seems to just work with no setup. I will try to write that down somewhere later.

**Comment by mikaelmello** [comment]
Great! I'll close the issue then
