### ISSUE TITLE
Extension crashing when updating Max Test Lines config

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#11]
Happened twice, I wasn't sure at first but this confirms the behavior

![image](https://user-images.githubusercontent.com/17488630/58387014-a4735580-7fde-11e9-895f-be37e397904f.png)
![image](https://user-images.githubusercontent.com/17488630/58387018-a9d0a000-7fde-11e9-845c-0e2efb499738.png)

**Comment by pustaczek** [comment]
Yeah, I will have to add error handling to config. Right now there really isn't any, but it seems to complain that the entered value is not a usize.

**Comment by mikaelmello** [comment]
Yes, testing again it crashes when I delete the current value and unfocus, sort of saving the change.
