### ISSUE TITLE
How to reset login credentials?

### ISSUE THREAD

**Issue by GaurangTandon** [pustaczek/icie#12]
Thanks for the extension! I accidentally entered incorrect login details on the first try, now every time I press Alt-F11 it reuses my old credentials and I cannot figure out a way to reset them.

Where are the credentials stored? If encrypted (hopefully yes), how can I reset them?

**Comment by pustaczek** [comment]
Passwords are stored on the system keyring, which you can manage using the `seahorse` command. Find an entry called `Password for @credentials https://codeforces.com on icie` and delete it. I will add a way to reset them from VS Code in the next release.
