### ISSUE TITLE
force submit

### ISSUE THREAD

**Issue by dcrystalj** [pustaczek/icie#13]
is there a way to force submit? sometimes test samples are not exactly the same as solution output but still correct

**Comment by pustaczek** [comment]
Hi! If you click on the ✓ action inside the output cell(version 0.5.1+), your output will be marked as correct and submit will consider that test as passed.

**Comment by dcrystalj** [comment]
I am on 0.5.4 
![image](https://user-images.githubusercontent.com/1460727/59566952-29461200-9067-11e9-8a0d-e99cd5e1433d.png)

**Comment by pustaczek** [comment]
Actions buttons are displayed when you hover over the cell - move your mouse on top of the red area and the button will appear.

**Comment by dcrystalj** [comment]
oh.. well hidden :D  but it works. thank you

**Comment by pustaczek** [comment]
Thank you for saying this, too - I will try to make actions more discoverable in the next update.
