### ISSUE TITLE
Can't save username and password in archlinux + KDE with kwallet installed.

### ISSUE THREAD

**Issue by Howard-00** [pustaczek/icie#14]

**Comment by pustaczek** [comment]
Hi! Could you click Help > Toggle Developer Tools > Console in VS Code, try to trigger the error again and find any lines starting with "keyring errored, details: "? This may provide some more information, athough I use [keyring-rs](https://github.com/hwchen/keyring-rs) for keyring handling so I don't really know why it fails.

**Comment by pustaczek** [comment]
This is apparently a [long-standing issue](https://github.com/atom/node-keytar/issues/74) with KDE Wallet. You need to install and configure [GNOME Keyring](https://wiki.archlinux.org/index.php/GNOME/Keyring), which will fix the error as tested on a VM
