### ISSUE TITLE
Way to resolve multiple problem statement error in atcoder

### ISSUE THREAD

**Issue by mjguru** [pustaczek/icie#15]
Consider https://atcoder.jp/contests/arc063/tasks/arc063_c. This gets the error that multiple problem statement is found for english in the html structure. Maybe there could be a way around this?

**Comment by pustaczek** [comment]
Hi, thanks for the bug report! The error happened due to the presence of the second output in the first test case, which confused the HTML scrapper. I made a fix and pushed it as a part of the 0.5.7 release, so this should work now :)
