### ISSUE TITLE
Add support to start contest from group 

### ISSUE THREAD

**Issue by bruce-willis** [pustaczek/icie#18]
I would like to start contest from group, like this one: https://codeforces.com/group/IlJnKl8rCy/contest/253558  

Nowadays, if I enter this url I will get `wrong task URL format; report issue?` error.

Thanks

**Comment by pustaczek** [comment]
Hi! Sorry for the long wait, but it's done now. I will try to release it sometime soon in 0.7, because there was a rather large internal rewrite recently, and I need to test it. Thank you for reporting this!
