### ISSUE TITLE
unexpected HTML structure (External("unrecognized logic outcome") at [External]);

### ISSUE THREAD

**Issue by shubhamgupta107** [pustaczek/icie#19]
I am not able to submit by pressing Alt + F12. The above is showing.

**Comment by pustaczek** [comment]
Hi, thanks for the report! May I ask what site are you using, Codeforces or Atcoder or ...? It this a first login, or have you been logged in already? I've just checked and all of them seem to mostly work, aside from CodeChef, which is broken in a different way; possibly this is related.

**Comment by shubhamgupta107** [comment]
It's on Codeforces and I have made the login successfully. But as I am submitting the practice problem it is stating that error.
On Codechef too , I am unable to submit the practice problem, though the problem is different.

**Comment by theMasix** [comment]
Same issue is there. It's my first login to codeforces and I wanna participate in codeforces round.

**Comment by pustaczek** [comment]
I somehow don't get this error no matter what I do. I've added some more logging to these areas (yay printf debugging...) and released 0.7.1. @shubhamgupta107 @theMasix Could you please download 0.7.1, try to submit some task to get the error, and send [log messages screenshots](https://i.imgur.com/z7KjxJC.png) either here or to my email (mateusz@cegla.net)?

**Comment by Anachor** [comment]
Hi, I have the same error. I'm trying submit on atcoder. It was first time logging in.

**Comment by pustaczek** [comment]
Huge thanks for the info! The atcoder one is a different bug, which happened to be easier to track down, but I think they may have the same underlying reason (although I still don't know exactly why I can't reproduce this on codeforces). I will try to come up with a solution in the next few days.

As a workaround, you can likely try uninstalling the extension, downloading [0.6.4 .vsix] and [installing it manually]. Don't forget to update to 0.7.2 when it comes out!

[0.6.4 .vsix]: https://github.com/pustaczek/icie/releases/tag/0.6.4
[installing it manually]: https://i.imgur.com/jfma0sO.png

**Comment by pustaczek** [comment]
Okay, so I released 0.7.2 with a fix for the AtCoder problem. I also hope that will fix the Codeforces issue, because this bug could affect other sites in really unpredictable ways.
