### ISSUE TITLE
some bug in windows

### ISSUE THREAD

**Issue by zoolily** [pustaczek/icie#20]
EINVAL: invalid argument, mkdir 'C:\Users\XH\◉
					atcoder-beginner-contest-155'; [report issue?](https://github.com/pustaczek/icie/issues)

when i create contest shows that.
and how can i choose path when it create new contest?

**Comment by pustaczek** [comment]
Press <kbd>Ctrl</kbd><kbd>,</kbd> to open VS Code settings. There, go to Extensions > ICIE and find the setting called 'Icie Dir Project Directory'.

**Comment by zoolily** [comment]
mkdir error also, i think that is cause by '◉', please check where is come from?

**Comment by pustaczek** [comment]
I fixed it, but you need to update the plugin to 0.7.2.
