### ISSUE TITLE
Error Displaying ICIE Test View After Version 0.7.18

### ISSUE THREAD

**Issue by Jumpmelon** [pustaczek/icie#31]
After updated to 0.7.18, it seems unusal displaying ICIE Test View, and all the buttons (Copy, Edit, ...) don't work.

![QQ截图20200512234342](https://user-images.githubusercontent.com/19512495/81715173-7bc3c480-94aa-11ea-9c81-15a7f35e8724.png)

Thanks.

**Comment by pustaczek** [comment]
Which version of VS Code are you using? The new UI was tested with 1.44, but since it's HTML/CSS under the hood it's very much possible that something was accidentally broken on older versions. If you are using an older version, please try upgrading to 1.44 or later.

**Comment by Jumpmelon** [comment]
> 
> 
> Which version of VS Code are you using? The new UI was tested with 1.44, but since it's HTML/CSS under the hood it's very much possible that something was accidentally broken on older versions. If you are using an older version, please try upgrading to 1.44 or later.
> 
> Or actually, this could be Windows specific. I'll look into this.

Thanks for your reply.
I'm using VS Code 1.45.0 (the latest) in Windows 10.
![图片](https://user-images.githubusercontent.com/19512495/81717853-a8c5a680-94ad-11ea-8e9d-c52405513b81.png)
(Or do I need to downgrade to 1.44 and test it?

**Comment by Jumpmelon** [comment]
> 
> 
> > Which version of VS Code are you using? The new UI was tested with 1.44, but since it's HTML/CSS under the hood it's very much possible that something was accidentally broken on older versions. If you are using an older version, please try upgrading to 1.44 or later.
> > Or actually, this could be Windows specific. I'll look into this.
> 
> Thanks for your reply.
> I'm using VS Code 1.45.0 (the latest) in Windows 10.
> ![图片](https://user-images.githubusercontent.com/19512495/81717853-a8c5a680-94ad-11ea-8e9d-c52405513b81.png)
> (Or do I need to downgrade to 1.44 and test it?

I have downgraded to 1.44.2 and found it still not working.
![图片](https://user-images.githubusercontent.com/19512495/81718443-53d66000-94ae-11ea-9f57-109a876497ee.png)

**Comment by pustaczek** [comment]
Yeah, it turned out to be a Windows issue (yay Windows paths!). I'll fix it in a moment and push it as 0.7.20.

**Comment by Jumpmelon** [comment]
> 
> 
> Yeah, it turned out to be a Windows issue (yay Windows paths!). I'll fix it in a moment and push it as 0.7.20.

OK. Thanks a lot.
