### ISSUE TITLE
Options to use vscode integrated terminal for debugging

### ISSUE THREAD

**Issue by lituzou** [pustaczek/icie#32]
When I use WSL to debug the file, the extension simply crash. I think it has something to do with the external terminal which cannot be triggered under WSL.
Is it possible to use vscode integrated terminal to debug?

**Comment by pustaczek** [comment]
I have implemented a fallback to the integrated terminal that will trigger automatically if the external one doesn't work, and also fixed the mentioned crash. I haven't actually tested it on WSL (my Windows install seems to be broken...), but it should work once I release 0.7.22.
