### ISSUE TITLE
Unrecognized verdict in Codechef

### ISSUE THREAD

**Issue by Raju235** [pustaczek/icie#35]
Not able to recognize some of the verdicts in Codechef.
Encountering the following error.

![image](https://user-images.githubusercontent.com/31474577/85108717-cf55ca80-b22d-11ea-9720-1fae0267b12e.png)

Verdict for the above submission was this:

![image](https://user-images.githubusercontent.com/31474577/85109163-83575580-b22e-11ea-8795-0c373fc04a8b.png)

I'm not sure about what might be the problem.
I guess adding some of the verdicts that are not defined <a href="https://github.com/pustaczek/icie/blob/5c39ddf0e5bc5de45a0411751bc707a607b232a2/unijudge-codechef/src/lib.rs#L155">here</a> could solve the problem.

Getting the same error for both ''Correct Answer' and 'Wrong Answer' responses.

**Comment by pustaczek** [comment]
It seems so, but it's name is empty (not missing, but ""). I think it's probably some kind of rare version of the "pending" verdict I never happened to encounter when developing. I'll just assume that's the case and release a 0.7.25.
