### ISSUE TITLE
Test View not working properly in VSC version 1.47.0

### ISSUE THREAD

**Issue by kshitijalwadhi** [pustaczek/icie#38]
After the latest VS code update, the ICIE Test View (Alt + 0) is not displaying properly. I have added a screenshot. 

VS Code version : 1.47.0
ICIE extension version : 0.7.25

<img width="382" alt="Capture" src="https://user-images.githubusercontent.com/52427677/87224613-579a3c00-c3a4-11ea-9531-d4205ba38ce6.PNG">

**Comment by pustaczek** [comment]
Does closing and opening the tab fix the issue? There were some ongoing issues with this recently (see microsoft/vscode#101093), but restarting the tab usually fixes this. If not, I could release a workaround since it's not too bad.

**Comment by kshitijalwadhi** [comment]
Thanks for replying. 
Restarting the tab doesn't fix it. The UI is still the same.

**Comment by pustaczek** [comment]
I have released 0.7.26 with a fix, it should go live in about half an hour.
