### ISSUE TITLE
Can't track submissions anymore

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#4]
Yesterday I could track the result of my submissions without any errors, today after 0.5.2 came out, something is happening: 

![image](https://user-images.githubusercontent.com/17488630/58373781-08781a00-7f0a-11e9-9ad5-34e959fa0b6f.png)

I tried to revert back to 0.5.1 but it kept happening. I'll try to run with a debug version and get a better stack trace

**Comment by mikaelmello** [comment]
https://github.com/pustaczek/icie/blob/master/src/submit.rs#L33

![image](https://user-images.githubusercontent.com/17488630/58374871-89401180-7f1c-11e9-8939-192b006abf1c.png)

**Comment by pustaczek** [comment]
A better backtrace was lost due to sloppy error conversion. I will fix it in a second, and a more sensible error message should appear.

**Comment by pustaczek** [comment]
Try reproducing the issue now. Aside from that unlucky conversion, the error handling in codeforces is more or less robust.

**Comment by mikaelmello** [comment]
Here it is, got an AC at least haha

[-1558822937959.log](https://github.com/pustaczek/icie/files/3219803/-1558822937959.log)
[-1558822944830.log](https://github.com/pustaczek/icie/files/3219804/-1558822944830.log)

![image](https://user-images.githubusercontent.com/17488630/58375132-95c76880-7f22-11e9-9de8-092daa599a2f.png)

**Comment by pustaczek** [comment]
The hacked verdict was not handled. The appropriate if was added and everything should work now.

**Comment by mikaelmello** [comment]
![image](https://user-images.githubusercontent.com/17488630/58375198-0a4ed700-7f24-11e9-9fd7-762e90e5ab4c.png)

All working now! Thanks!
