### ISSUE TITLE
website could not be analyzed; missing field `problem_name` at line 2 column 82;

### ISSUE THREAD

**Issue by KushagraMehta** [pustaczek/icie#45]
Happened for [January Challenge 2021 Division 3](https://www.codechef.com/JAN21C)

**Comment by pustaczek** [comment]
CodeChef apparently sometimes sends a response that says the problem is "not visible", even long after the contest has started. I fixed this for version 1.0.1, which will retry the request in case this happens. It should go live in about half an hour.
