### ISSUE TITLE
Stress Test is never stopping

### ISSUE THREAD

**Issue by gratus907** [pustaczek/icie#48]
Hello. First of all, thanks for the great work! 

Recently, I have noticed that stress testing does not stop when I close the tab. If I found a suitable testcase which brute-force and main result differs, I think what we want is to add the 'found counterexample' to our testset by clicking plus and stress testing should stop, thus enabling user to use icie after debugging my code. However, it seems ICIE is stuck here.

Below is the image which shows what the issue is. When I tried to add test 1, ICIE immediately hanged. 
![image](https://user-images.githubusercontent.com/20734325/127551966-0b6098bb-659c-4dde-9376-b652ffe938e2.png)

Here is a screenshot where I closed ICIE Stress test tab. As seen in lower left side of the screenshot, stress testing is keep running(also no test is actually done), and I cannot use usual testing (ALT + 0), another launch of stress test, and so. 
![image](https://user-images.githubusercontent.com/20734325/127552817-a7b0c5ae-1f6a-4ed1-9bfc-81c8226a2fef.png)
Currently, it seems like only way to clear the stress test is to close VSCode. However by this I lose the counterexample I found. Is there a way to resolve this issue? It would be great if I myself can fix this, but I know nothing about Rust...

**Comment by gratus907** [comment]
Although not always replicable every time, when I close ICIE tab, sometimes it shows following message.
```
ICIE panicked, called 'Option::unwrap()' on a 'None' value at vscode-sys/src/lib.rs:116:1;
```
I have no idea if this is relevant, but it seems suspicious since only time I see that message is when I close ICIE stress test tab.
Thanks for great work.

**Comment by unneon** [comment]
I fixed the issue, it turns out a new VS Code version decided to change the behavior when using a closed webview. It used to return false, but now it returns an Error object. Assuming the release pipeline still works, 1.0.2 should go live in about half an hour.

**Comment by gratus907** [comment]
It works nicely. Thanks :)
