### ISSUE TITLE
Truncate display of large input/output text in ICIE Test View

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#7]
Large inputs/outputs aren't visually relevant, we usually just want them to match with our program. When there is a large input/output the test view lags and it becomes very hard to visualize anything, especially the small ones.

![image](https://user-images.githubusercontent.com/17488630/58384648-93b0e880-7fba-11e9-825d-450cef7f127a.png)

**Comment by pustaczek** [comment]
The CSS in this project has... a number of issues. I have to learn how to write it properly, but I'll try to fix all that sometime soon.

**Comment by pustaczek** [comment]
CSS refactor is done, test cells now have fixed width and support scrolling. If it is necessary, it is also possible to reimplement line wrapping as a configurable alternative. Does this change solve this problem?

**Comment by mikaelmello** [comment]
Yes, it does, I'm going to close the issue, thanks!
